### ISSUE TITLE
Missing notification permission

### ISSUE THREAD

**Issue by AeliusSaionji** [CurtisMJ/LogoPlus#11]
The passive and battery effects work for me, but I cannot get notifications to work at all. The notification permission is not listed within the system settings for the app, so I cannot manually grant it.

Chroma is disabled and I'm not sure if there's anything else I should be doing on my end.

**Comment by CurtisMJ** [comment]
Hi, 
The notification permission is indeed not present as it is a special kind.
You'll find the option to grant it in Settings -> Apps & notifications -> Advanced -> Special app access -> Notification access. Simply flip the toggle next to Logo+

**Comment by AeliusSaionji** [comment]
Ugh android has 7 of these menus hidden around different settings pages, I thought I checked them all.

Thank you, and sorry for wasting your time!
